name: quiz
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  device_info: ^2.0.3
  package_info: ^2.0.2
  url_launcher: ^6.1.14
  logger: ^2.0.2+1
  flutter_riverpod: ^2.4.3
  riverpod_annotation: ^2.2.0
  go_router: ^12.1.1
  hooks_riverpod: ^2.4.3
  cached_network_image: ^3.3.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  flutter_native_splash: ^2.3.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dio: ^5.3.3
  connectivity: ^3.0.6
  dio_smart_retry: ^6.0.0
  jazzicon: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_speed_dial: ^7.0.0
  easy_refresh: ^3.3.2+4
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  isar_generator: ^3.1.0+1
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9
  custom_lint: ^0.5.7

flutter:
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section.
  assets:
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
  class_name: L
  main_locale: en